Repository redhat-performance/benchmark-runner, pull requests merged in 2023-08, with the labels that each got.

#633 Install latest OCP and kata
  .github/workflows/Weekly_Func_Env_Operator_CI.yml
  .github/workflows/Weekly_Perf_Env_Installer_CI.yml
  .github/workflows/Weekly_Perf_Env_Operator_CI.yml
Labels: bug

#637 fix bootstorm vm
  .github/workflows/Nightly_Perf_Env_CI.yml
Labels: bug

#636 Adding the pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#639 Fix elasticsearch index widget
  benchmark_runner/common/elasticsearch/elasticsearch_operations.py
  benchmark_runner/jupyterlab/templates/elasticsearch_operations/elasticsearch_widgets.py
  tests/integration/benchmark_runner/common/elasticsearch/test_elasticsearch_operations.py
Labels: bug, ok-to-test

#638 Check if Kata/ CNV operators are installed
  benchmark_runner/benchmark_operator/benchmark_operator_exceptions.py
  benchmark_runner/benchmark_operator/benchmark_operator_workloads.py
  benchmark_runner/benchmark_operator/benchmark_operator_workloads_operations.py
  benchmark_runner/benchmark_operator/hammerdb_pod.py
  benchmark_runner/benchmark_operator/hammerdb_vm.py
  benchmark_runner/benchmark_operator/stressng_pod.py
  benchmark_runner/benchmark_operator/stressng_vm.py
  benchmark_runner/benchmark_operator/uperf_pod.py
  benchmark_runner/benchmark_operator/uperf_vm.py
  benchmark_runner/common/oc/oc.py
  benchmark_runner/workloads/bootstorm_vm.py
  benchmark_runner/workloads/vdbench_pod.py
  benchmark_runner/workloads/vdbench_vm.py
  benchmark_runner/workloads/windows_vm.py
  benchmark_runner/workloads/workloads.py
  benchmark_runner/workloads/workloads_exceptions.py
  benchmark_runner/workloads/workloads_operations.py
Labels: enhancement, ok-to-test

#641 PerfCi Grafana Dashboard: add grafonnet support
  .github/workflows/Nightly_Perf_Env_CI.yml
  .github/workflows/Perf_Env_Build_Test_CI.yml
  .github/workflows/Perf_Env_PR_Test_CI.yml
  .gitignore
  HOW_TO.md
  README.md
  benchmark_runner/common/grafana/__init__.py
  benchmark_runner/common/grafana/grafana_operations.py
  benchmark_runner/common/grafana/update_grafana_last_value_mappings.py
  benchmark_runner/grafana/Dockerfile
  benchmark_runner/grafana/__init__.py
  benchmark_runner/grafana/func/benchmark-runner-report.json
  benchmark_runner/grafana/func/benchmark-runner-summary-line-report-final.json
  benchmark_runner/grafana/func/dashboard.json
  benchmark_runner/grafana/func/system-metrics-report.json
  benchmark_runner/grafana/perf/Makefile
  benchmark_runner/grafana/perf/dashboard.json
  benchmark_runner/grafana/perf/dashboard.tf
  benchmark_runner/grafana/perf/extract_dashboard.py
  benchmark_runner/grafana/perf/jsonnet/g.libsonnet
  benchmark_runner/grafana/perf/jsonnet/jsonnetfile.json
  benchmark_runner/grafana/perf/jsonnet/jsonnetfile.lock.json
  benchmark_runner/grafana/perf/jsonnet/main.libsonnet
  benchmark_runner/grafana/update_grafana_dashboard.py
  benchmark_runner/grafana/update_main_libsonnet_versions.py
  benchmark_runner/main/environment_variables.py
  grafana/perf/PerfCI-Regression-Summary.json
  tests/integration/benchmark_runner/common/grafana/__init__.py
  tests/integration/benchmark_runner/common/grafana/test_grafana_operations.py
  tests/integration/benchmark_runner/test_environment_variables.py
Labels: enhancement, ok-to-test

#642 fix build order
  .github/workflows/Perf_Env_Build_Test_CI.yml
  tests/integration/benchmark_runner/common/grafana/test_grafana_operations.py
  tests/integration/benchmark_runner/test_environment_variables.py
Labels: bug, ok-to-test

#643 fix grafana job
  .bumpversion.cfg
  .github/workflows/Nightly_Perf_Env_CI.yml
  .github/workflows/Perf_Env_Build_Test_CI.yml
  benchmark_runner/grafana/update_versions_main_libsonnet.py
  setup.py
Labels: bug, ok-to-test

#644 fix python run
  .github/workflows/Nightly_Perf_Env_CI.yml
  .github/workflows/Perf_Env_Build_Test_CI.yml
  benchmark_runner/common/grafana/update_grafana_latest_value_mappings.py
  benchmark_runner/grafana/update_versions_main_libsonnet.py
Labels: bug

#645 update package version
  .bumpversion.cfg
  setup.py
Labels: bug
