Repository redhat-performance/benchmark-runner, pull requests merged in 2023-01, with the labels that each got.

#521 reduce bootstorm vm Fedora37 memory
  benchmark_runner/common/template_operations/templates/bootstorm/bootstorm_data_template.yaml
  benchmark_runner/main/environment_variables.py
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_bootstorm_vm_ODF_PVC_False/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_bootstorm_vm_ODF_PVC_True/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_bootstorm_vm_ODF_PVC_False/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_bootstorm_vm_ODF_PVC_True/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_bootstorm_vm_ODF_PVC_False/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_bootstorm_vm_ODF_PVC_True/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_bootstorm_vm_ODF_PVC_False/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_bootstorm_vm_ODF_PVC_True/bootstorm_vm.yaml
Labels: bug

#522 decrease bootstorm vm memory
  benchmark_runner/common/template_operations/templates/bootstorm/bootstorm_data_template.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_bootstorm_vm_ODF_PVC_False/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_bootstorm_vm_ODF_PVC_True/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_bootstorm_vm_ODF_PVC_False/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_bootstorm_vm_ODF_PVC_True/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_bootstorm_vm_ODF_PVC_False/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_bootstorm_vm_ODF_PVC_True/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_bootstorm_vm_ODF_PVC_False/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_bootstorm_vm_ODF_PVC_True/bootstorm_vm.yaml
Labels: bug, enhancement

#523 bootsotrm fix delete vms
  benchmark_runner/workloads/bootstorm_vm.py
Labels: bug

#525 bootstom fix delete vm
  benchmark_runner/common/oc/oc.py
  benchmark_runner/common/oc/oc_exceptions.py
  benchmark_runner/workloads/bootstorm_vm.py
Labels: bug

#526 revert delete vms flow
  benchmark_runner/workloads/bootstorm_vm.py
Labels: bug, Approved

#527 Enable BootStorm VM in Performance CI
  .github/workflows/Nightly_Func_Env_CI.yml
  .github/workflows/Nightly_Perf_Env_CI.yml
  .github/workflows/Release_ClusterBuster_Perf_Env_CI.yml
  .github/workflows/Weekly_Func_Env_Installer_CI.yml
  .github/workflows/Weekly_Func_Env_Operator_CI.yml
  .github/workflows/Weekly_Perf_Env_Installer_CI.yml
  .github/workflows/Weekly_Perf_Env_Operator_CI.yml
Labels: enhancement, Approved

#528 Set virtiofsd_threadpoolsize appropriately for vdbench
  benchmark_runner/common/template_operations/templates/vdbench/internal_data/vdbench_pod_template.yaml
  benchmark_runner/common/template_operations/templates/vdbench/vdbench_data_template.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_vdbench_kata_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_vdbench_kata_ODF_PVC_True/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_vdbench_kata_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_vdbench_kata_ODF_PVC_True/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_vdbench_kata_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_vdbench_kata_ODF_PVC_True/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_vdbench_kata_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_vdbench_kata_ODF_PVC_True/vdbench_pod.yaml
Labels: bug, enhancement, Approved

#529 update bootstorm vm in readthedocs
  docs/source/podman.md
Labels: bug, Approved

#530 update vdbench limit memory to 64GB
  benchmark_runner/common/template_operations/templates/vdbench/vdbench_data_template.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_vdbench_kata_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_vdbench_kata_ODF_PVC_True/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_vdbench_pod_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_vdbench_pod_ODF_PVC_True/vdbench_pod.yaml
Labels: bug, Approved

#531 vdbench remove memory limit
  benchmark_runner/common/template_operations/templates/vdbench/internal_data/vdbench_pod_template.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_vdbench_kata_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_vdbench_kata_ODF_PVC_True/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_vdbench_kata_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_vdbench_kata_ODF_PVC_True/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_vdbench_kata_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_vdbench_kata_ODF_PVC_True/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_vdbench_kata_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_vdbench_kata_ODF_PVC_True/vdbench_pod.yaml
Labels: bug, Approved

#533 vm termination fix
  benchmark_runner/common/template_operations/templates/bootstorm/internal_data/bootstorm_vm_template.yaml
  benchmark_runner/common/template_operations/templates/vdbench/internal_data/vdbench_vm_template.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_bootstorm_vm_ODF_PVC_False/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_bootstorm_vm_ODF_PVC_True/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_vdbench_vm_ODF_PVC_False/vdbench_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_vdbench_vm_ODF_PVC_True/vdbench_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_bootstorm_vm_ODF_PVC_False/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_bootstorm_vm_ODF_PVC_True/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_vdbench_vm_ODF_PVC_False/vdbench_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_vdbench_vm_ODF_PVC_True/vdbench_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_bootstorm_vm_ODF_PVC_False/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_bootstorm_vm_ODF_PVC_True/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_vdbench_vm_ODF_PVC_False/vdbench_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_vdbench_vm_ODF_PVC_True/vdbench_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_bootstorm_vm_ODF_PVC_False/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_bootstorm_vm_ODF_PVC_True/bootstorm_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_vdbench_vm_ODF_PVC_False/vdbench_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_vdbench_vm_ODF_PVC_True/vdbench_vm.yaml
Labels: Approved

#534 Bootstorm:add vm stop
  benchmark_runner/workloads/bootstorm_vm.py
Labels: bug, Approved

#535 disable functional environment
  .github/workflows/Build_runner.yml
  .github/workflows/Nightly_Func_Env_CI.yml
  .github/workflows/Nightly_Perf_Env_CI.yml
  .github/workflows/Perf_Env_Build_Test_CI.yml
  .github/workflows/Perf_Env_E2E_Test_CI.yml
  .github/workflows/Perf_Env_PR_Test_CI.yml
  .github/workflows/Weekly_Func_Env_Installer_CI.yml
  .github/workflows/Weekly_Func_Env_Operator_CI.yml
  .github/workflows/Weekly_Perf_Env_Installer_CI.yml
  benchmark_runner/common/clouds/IBM/ibm_operations.py
  benchmark_runner/main/environment_variables.py
Labels: enhancement, Approved
