Repository redhat-performance/benchmark-runner, pull requests merged in 2023-09, with the labels that each got.

#646 update readme
  README.md
  docs/source/podman.md
Labels: bug

#647 fix artifact logs links
  .github/workflows/Nightly_Perf_Env_CI.yml
  benchmark_runner/grafana/perf/jsonnet/main.libsonnet
Labels: bug

#649 update python path
  .github/workflows/Nightly_Perf_Env_CI.yml
  .github/workflows/Perf_Env_Build_Test_CI.yml
Labels: bug

#648 vdbench vm image warmup
  .github/workflows/Nightly_Perf_Env_CI.yml
Labels: bug

#650 fix Grafana path
  .github/workflows/Nightly_Perf_Env_CI.yml
  .github/workflows/Perf_Env_Build_Test_CI.yml
  .github/workflows/Perf_Env_PR_Test_CI.yml
Labels: bug

#652 Update grafana job
  .github/workflows/Perf_Env_Build_Test_CI.yml
Labels: bug

#653 update last elastic fetch days
  benchmark_runner/common/grafana/update_grafana_latest_value_mappings.py
Labels: bug

#654 Update Prometheus VM memory metrics
  benchmark_runner/common/prometheus/metrics-default.yaml
  benchmark_runner/common/prometheus/prometheus_metrics_operations.py
  benchmark_runner/grafana/perf/jsonnet/main.libsonnet
  benchmark_runner/workloads/bootstorm_vm.py
  benchmark_runner/workloads/vdbench_vm.py
  benchmark_runner/workloads/windows_vm.py
  benchmark_runner/workloads/workloads_operations.py
Labels: enhancement, ok-to-test

#657 fix parse prometheus vdbench pod
  benchmark_runner/workloads/vdbench_pod.py
Labels: bug

#656 Update to clusterbuster-v1.2.2-kata-ci. See those release notes for explanation.
  Dockerfile
Labels: bug

#655 Update Grafana dashboard in dedicate folder
  .github/workflows/Nightly_Perf_Env_CI.yml
  .github/workflows/Perf_Env_Build_Test_CI.yml
  benchmark_runner/common/grafana/grafana_operations.py
  benchmark_runner/grafana/update_grafana_dashboard.py
  benchmark_runner/main/environment_variables.py
  tests/integration/benchmark_runner/common/grafana/test_grafana_operations.py
  tests/integration/benchmark_runner/test_environment_variables.py
Labels: enhancement, ok-to-test

#658 Fix auto push grafana json issue
  .github/workflows/Nightly_Perf_Env_CI.yml
  .github/workflows/Perf_Env_Build_Test_CI.yml
Labels: bug

#659 Fix artifacts grafonnet urls & clusterbuster artifacts panel
  benchmark_runner/grafana/perf/jsonnet/main.libsonnet
Labels: bug

#663 update ci status url link
  benchmark_runner/grafana/perf/jsonnet/main.libsonnet
Labels: enhancement

#664 Fix push grafana json issue
  .github/workflows/Nightly_Perf_Env_CI.yml
  .github/workflows/Perf_Env_Build_Test_CI.yml
Labels: bug

#665 fix windows warmup - PerfCi failed due to this issue
  .github/workflows/Nightly_Perf_Env_CI.yml
Labels: bug

#666 fix ci status url
  benchmark_runner/grafana/perf/jsonnet/main.libsonnet
Labels: bug

#667 fix push grafana json
  .github/workflows/Nightly_Perf_Env_CI.yml
  .github/workflows/Perf_Env_Build_Test_CI.yml
Labels: bug

#660 install latest 4.14.0-rc
  .github/workflows/Perf_Env_Build_Test_CI.yml
  .github/workflows/Perf_Env_PR_Test_CI.yml
  .github/workflows/Weekly_Func_Env_Installer_CI.yml
  .github/workflows/Weekly_Func_Env_Operator_CI.yml
  .github/workflows/Weekly_Perf_Env_Installer_CI.yml
  .github/workflows/Weekly_Perf_Env_Operator_CI.yml
  Dockerfile
Labels: enhancement

#669 fix oc client install
  .bumpversion.cfg
  Dockerfile
  setup.py
Labels: bug

#670 enable prometheus queries for all workloads
  benchmark_runner/benchmark_operator/benchmark_operator_workloads_operations.py
  benchmark_runner/benchmark_operator/hammerdb_pod.py
  benchmark_runner/benchmark_operator/hammerdb_vm.py
  benchmark_runner/benchmark_operator/stressng_pod.py
  benchmark_runner/benchmark_operator/stressng_vm.py
  benchmark_runner/benchmark_operator/uperf_pod.py
  benchmark_runner/benchmark_operator/uperf_vm.py
  benchmark_runner/grafana/perf/jsonnet/main.libsonnet
  benchmark_runner/workloads/bootstorm_vm.py
  benchmark_runner/workloads/vdbench_pod.py
  benchmark_runner/workloads/vdbench_vm.py
  benchmark_runner/workloads/windows_vm.py
Labels: enhancement, ok-to-test

#671 remove characters from value mapping
  benchmark_runner/common/grafana/update_grafana_latest_value_mappings.py
Labels: bug

#672 fix OCP 4.14 LSO issue
  .github/workflows/Nightly_Func_Env_CI.yml
  .github/workflows/Nightly_Perf_Env_CI.yml
  benchmark_runner/benchmark_operator/benchmark_operator_workloads_operations.py
  benchmark_runner/common/oc/oc.py
  benchmark_runner/main/environment_variables.py
  tests/integration/benchmark_runner/common/oc/test_oc.py
Labels: bug, ok-to-test

#677 update grafonnet commit
  .github/workflows/Perf_Env_Build_Test_CI.yml
Labels: bug

#675 Remove vm max memory from grafana
  benchmark_runner/grafana/perf/jsonnet/main.libsonnet
Labels: bug

#676 update clusterbuster uperf grafonnet
  benchmark_runner/grafana/perf/jsonnet/main.libsonnet
Labels: bug

#678 Add readthedocs conf file
  .readthedocs.yaml
Labels: bug
