Repository redhat-performance/benchmark-runner, pull requests merged in 2023-02, with the labels that each got.

#536 reduce bootstorm vms from 600 to 300 vms
  .github/workflows/Nightly_Perf_Env_CI.yml
  benchmark_runner/main/environment_variables.py
Labels: bug, Approved

#537 Remove memory limit pod
  HOW_TO.md
  Makefile
  benchmark_runner/common/ocp_resources/create_kata.py
  benchmark_runner/common/ocp_resources/kata/template/04_ocp_patch_runtimeclass_memory_overhead.sh
  benchmark_runner/common/template_operations/template_operations.py
  benchmark_runner/common/template_operations/templates/vdbench/internal_data/vdbench_pod_template.yaml
  benchmark_runner/common/template_operations/templates/vdbench/internal_data/vdbench_vm_template.yaml
  benchmark_runner/common/template_operations/templates/vdbench/vdbench_data_template.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_vdbench_kata_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_vdbench_kata_ODF_PVC_True/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_vdbench_kata_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_vdbench_kata_ODF_PVC_True/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_vdbench_pod_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_vdbench_pod_ODF_PVC_True/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_vdbench_kata_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_vdbench_kata_ODF_PVC_True/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_vdbench_kata_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_vdbench_kata_ODF_PVC_True/vdbench_pod.yaml
Labels: enhancement, Approved

#539 Bootstorm enable prometheus metrics
  MANIFEST.in
  benchmark_runner/common/prometheus/metrics-default.yaml
  benchmark_runner/common/prometheus/metrics-examples.yaml
  benchmark_runner/common/prometheus/prometheus_metrics_operations.py
  benchmark_runner/main/environment_variables.py
  benchmark_runner/workloads/bootstorm_vm.py
  benchmark_runner/workloads/workloads_operations.py
Labels: enhancement, Approved

#540 fix python3.10 ctype error
  Dockerfile
Labels: bug

#541 enable prometheus metrics for vdbench
  benchmark_runner/workloads/vdbench_pod.py
  benchmark_runner/workloads/vdbench_vm.py
  benchmark_runner/workloads/workloads_operations.py
  requirements.txt
  setup.py
Labels: enhancement, Approved

#542 update Grafana dashboard
  benchmark_runner/common/prometheus/metrics-default.yaml
  docs/source/develop.md
  grafana/perf/PerfCI-Regression-Summary.json
  grafana/perf/regression-summary.json
Labels: enhancement, Approved

#543 Revert kata memory patch fix vdbench limit
  benchmark_runner/common/ocp_resources/kata/template/04_ocp_patch_runtimeclass_memory_overhead.sh
  benchmark_runner/common/template_operations/templates/vdbench/internal_data/vdbench_pod_template.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_vdbench_kata_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_vdbench_kata_ODF_PVC_True/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_vdbench_kata_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_vdbench_kata_ODF_PVC_True/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_vdbench_kata_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_vdbench_kata_ODF_PVC_True/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_vdbench_kata_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_vdbench_kata_ODF_PVC_True/vdbench_pod.yaml
Labels: bug, Approved

#544 Workaround for actions/runner PR #1994 resulting in network error (connection reset by peer)
  .github/workflows/Weekly_Perf_Env_Installer_CI.yml
  .github/workflows/Weekly_Perf_Env_Operator_CI.yml
Labels: bug, Approved

#545 Socket exception: Connection reset by peer (104)
  .github/workflows/Weekly_Perf_Env_Installer_CI.yml
  .github/workflows/Weekly_Perf_Env_Operator_CI.yml
Labels: bug, Approved

#546 Revert docker to podman
  .github/workflows/Weekly_Perf_Env_Installer_CI.yml
  .github/workflows/Weekly_Perf_Env_Operator_CI.yml
Labels: bug

#547 update func ci on perf env
  .github/workflows/Nightly_Func_Env_CI.yml
  .github/workflows/Weekly_Func_Env_Installer_CI.yml
  .github/workflows/Weekly_Func_Env_Operator_CI.yml
  docs/source/develop.md
Labels: enhancement, Approved

#548 update prometheus path in elastic
  benchmark_runner/workloads/bootstorm_vm.py
Labels: bug, Approved

#549 update func to 4.13
  .github/workflows/Weekly_Func_Env_Installer_CI.yml
  .github/workflows/Weekly_Func_Env_Operator_CI.yml
Labels: enhancement

#550 update ec or fc version
  benchmark_runner/common/clouds/IBM/ibm_operations.py
Labels: bug

#552 fix bootstorm dirty mem spike
  benchmark_runner/workloads/workloads_operations.py
Labels: bug, Approved

#553 remove skip ocp remove
  benchmark_runner/main/main.py
Labels: enhancement, Approved

#555 clusterbuster solve permission issues
  Dockerfile
  README.md
  docs/source/podman.md
  tests/integration/benchmark_runner/common/elasticsearch/test_elasticsearch_operations.py
  tests/integration/benchmark_runner/common/oc/test_oc_benchmark_operator.py
  tests/integration/benchmark_runner/test_environment_variables.py
Labels: bug, Approved

#556 update_virtctl_0.58.1
  .github/workflows/Perf_Env_Build_Test_CI.yml
  .github/workflows/Perf_Env_PR_Test_CI.yml
  Dockerfile
Labels: enhancement

#560 fix_vdbench_pod_psa_error
  benchmark_runner/common/template_operations/templates/vdbench/internal_data/vdbench_pod_template.yaml
  benchmark_runner/main/environment_variables.py
  tests/integration/benchmark_runner/templates/vdbench_kata_template.yaml
  tests/integration/benchmark_runner/templates/vdbench_pod_template.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_vdbench_kata_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_vdbench_kata_ODF_PVC_True/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_vdbench_pod_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_vdbench_pod_ODF_PVC_True/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_vdbench_kata_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_vdbench_kata_ODF_PVC_True/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_vdbench_pod_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_vdbench_pod_ODF_PVC_True/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_vdbench_kata_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_vdbench_kata_ODF_PVC_True/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_vdbench_pod_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_vdbench_pod_ODF_PVC_True/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_vdbench_kata_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_vdbench_kata_ODF_PVC_True/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_vdbench_pod_ODF_PVC_False/vdbench_pod.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_vdbench_pod_ODF_PVC_True/vdbench_pod.yaml
Labels: bug, Approved

#564 update bootstorm vm func scale
  .github/workflows/Nightly_Func_Env_CI.yml
  .github/workflows/Nightly_Perf_Env_CI.yml
Labels: enhancement

#565 Bump clusterbuster version to v1.2.0-rc.2
  Dockerfile
Labels: bug
