Repository redhat-performance/benchmark-runner, pull requests merged in 2024-06, with the labels that each got.

#822 add pre commit check
  .pre-commit-config.yaml
  tests_requirements.txt
Labels: enhancement, Security alert, ok-to-test

#824 fix pre commit
  .pre-commit-config.yaml
  tests_requirements.txt
Labels: bug, ok-to-test

#826 Upgrading the base image in the Dockerfile to CentOS Stream 9
  .bumpversion.cfg
  Dockerfile
  setup.py
Labels: bug, enhancement

#823 Python 3.11 and 3.12 support
  .github/workflows/Nightly_Func_Env_CI.yml
  .github/workflows/Nightly_Perf_Env_CI.yml
  .github/workflows/Nightly_Perf_Env_CI_Scale.yml
  .github/workflows/Perf_Env_Build_Azure_Test_CI.yml
  .github/workflows/Perf_Env_Build_Test_CI.yml
  .github/workflows/Perf_Env_E2E_Test_CI.yml
  .github/workflows/Perf_Env_PR_Azure_Test_CI.yml
  .github/workflows/Perf_Env_PR_Test_CI.yml
  .github/workflows/Release_ClusterBuster_Perf_Env_CI.yml
  .github/workflows/Weekly_Func_Env_Installer_CI.yml
  .github/workflows/Weekly_Func_Env_Operator_CI.yml
  .github/workflows/Weekly_Perf_Env_Installer_CI.yml
  .github/workflows/Weekly_Perf_Env_Operator_CI.yml
  .readthedocs.yaml
  requirements.txt
  setup.py
  tests_requirements.txt
Labels: enhancement, ok-to-test

#827 fix pypi validate
  .bumpversion.cfg
  .github/workflows/Perf_Env_Build_Test_CI.yml
  setup.py
Labels: bug

#828 fix pypi validate
  .bumpversion.cfg
  .github/workflows/Perf_Env_Build_Test_CI.yml
  setup.py
Labels: bug

#829 fix setuptools
  .bumpversion.cfg
  .github/workflows/Perf_Env_Build_Test_CI.yml
  setup.py
Labels: bug

#830 fix setuptool
  .bumpversion.cfg
  .github/workflows/Perf_Env_Build_Test_CI.yml
  setup.py
Labels: bug

#833 Weekly IBM SNO workloads testing
  .github/workflows/Nightly_Perf_Env_CI.yml
Labels: enhancement

#831 Update python3.12 changes
  .github/workflows/Build_runner.yml
  .github/workflows/Perf_Env_Build_Azure_Test_CI.yml
  .github/workflows/Perf_Env_Build_Test_CI.yml
  Dockerfile
  benchmark_runner/common/elasticsearch/elasticsearch_operations.py
  requirements.txt
Labels: bug

#839 Update boto
  requirements.txt
  setup.py
Labels: bug

#844 Enhance pre-commit checks
  .pre-commit-config.yaml
  HOW_TO.md
  benchmark_runner/common/assisted_installer/jetlag/run_jetlag.sh
  benchmark_runner/common/ocp_resources/odf/template/01_delete_disks_template.sh
  benchmark_runner/common/template_operations/template_operations.py
  benchmark_runner/common/template_operations/templates/common_template.yaml
  benchmark_runner/common/template_operations/templates/windows/internal_data/windows_vm_template.yaml
  benchmark_runner/jupyterlab/templates/analyze_prometheus_logs/analyze_prometheus_logs.ipynb
  benchmark_runner/jupyterlab/templates/analyze_workloads/analyze_hammerdb_logs/analyze_hammerdb_logs.ipynb
  benchmark_runner/jupyterlab/templates/elasticsearch_operations/elasticsearch_operations.ipynb
  benchmark_runner/jupyterlab/templates/summary_report/update_summary_report_versions.ipynb
  ci_pod/create_ci_pod.sh
  ci_pod/delete_ci_pod.sh
  docs/PRE-COMMIT.md
  docs/source/develop.md
  generate_golden_files.sh
  requirements.txt
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_windows_vm_ODF_PVC_False/windows_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/func_ci_windows_vm_ODF_PVC_True/windows_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_windows_vm_ODF_PVC_False/windows_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/perf_ci_windows_vm_ODF_PVC_True/windows_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_windows_vm_ODF_PVC_False/windows_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/release_windows_vm_ODF_PVC_True/windows_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_windows_vm_ODF_PVC_False/windows_vm.yaml
  tests/unittest/benchmark_runner/common/template_operations/golden_files/test_ci_windows_vm_ODF_PVC_True/windows_vm.yaml
Labels: documentation, enhancement, cleanup, ok-to-test

#845 Python3.12 add setuptools
  requirements.txt
  setup.py
  tests_requirements.txt
Labels: bug, dependencies, ok-to-test

#846 Fix setup.py
  .bumpversion.cfg
  setup.py
Labels: bug

#848 Fix format issue
  benchmark_runner/common/clouds/BareMetal/bare_metal_operations.py
Labels: bug, ok-to-test

#849 Add delete s3 key test
  benchmark_runner/common/clouds/shared/s3/s3_operations.py
  benchmark_runner/common/clouds/shared/s3/s3_operations_exceptions.py
  tests/integration/benchmark_runner/common/clouds/shared/s3/test_s3_operations.py
Labels: enhancement, ok-to-test

#851 Remove sudo cmd
  jenkins/PerfCI_Grafana_Deployment/Jenkinsfile
Labels: bug, ok-to-test

#852 PerfCi backup and report job
  jenkins/PerfCI_Backup_Report_Deployment/Jenkinsfile
  jenkins/PerfCI_Grafana_Deployment/Jenkinsfile
Labels: enhancement
